# Copyright (C) 2011-2012 The CyanogenMod Project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is generated by device/huawei/hws7300u/extract-files.sh

# Prebuilt libraries that are needed to build open-source libraries
PRODUCT_COPY_FILES += \
	vendor/huawei/hws7300u/proprietary/lib/libacdbmapper.so:obj/lib/libacdbmapper.so \
	vendor/huawei/hws7300u/proprietary/lib/libaudioalsa.so:obj/lib/libaudioalsa.so \
	vendor/huawei/hws7300u/proprietary/lib/libacdbloader.so:obj/lib/libacdbloader.so  \
        vendor/huawei/hws7300u/proprietary/lib/libnv.so:obj/lib/libnv.so  \
        vendor/huawei/hws7300u/proprietary/lib/liboncrpc.so:obj/lib/liboncrpc.so \
        vendor/huawei/hws7300u/proprietary/lib/libmmjpeg.so:obj/lib/libmmjpeg.so

# Proprietary files
PRODUCT_COPY_FILES += \
	vendor/huawei/hws7300u/proprietary/media/charginganimation.zip:system/media/charginganimation.zip \
	vendor/huawei/hws7300u/proprietary/bin/charginganimation:system/bin/charginganimation \
	vendor/huawei/hws7300u/proprietary/bin/bootanimationex:system/bin/bootanimationex \
	vendor/huawei/hws7300u/proprietary/lib/libacdbmapper.so:system/lib/libacdbmapper.so \
	vendor/huawei/hws7300u/proprietary/lib/libaudioalsa.so:system/lib/libaudioalsa.so \
	vendor/huawei/hws7300u/proprietary/lib/libacdbloader.so:system/lib/libacdbloader.so \
	vendor/huawei/hws7300u/proprietary/lib/libaudcal.so:system/lib/libaudcal.so \
	vendor/huawei/hws7300u/proprietary/lib/libaudioparsers.so:system/lib/libaudioparsers.so \
	vendor/huawei/hws7300u/proprietary/lib/libmmparser.so:system/lib/libmmparser.so \
	vendor/huawei/hws7300u/proprietary/lib/libmmosal.so:system/lib/libmmosal.so \
	vendor/huawei/hws7300u/proprietary/bin/netmgrd:system/bin/netmgrd \
	vendor/huawei/hws7300u/proprietary/bin/qmiproxy:system/bin/qmiproxy \
	vendor/huawei/hws7300u/proprietary/bin/qmuxd:system/bin/qmuxd \
	vendor/huawei/hws7300u/proprietary/bin/rmt_storage:system/bin/rmt_storage \
	vendor/huawei/hws7300u/proprietary/bin/rmt_oeminfo:system/bin/rmt_oeminfo \
	vendor/huawei/hws7300u/proprietary/lib/libqmi.so:system/lib/libqmi.so \
	vendor/huawei/hws7300u/proprietary/lib/libqmiservices.so:system/lib/libqmiservices.so \
	vendor/huawei/hws7300u/proprietary/lib/libqdi.so:system/lib/libqdi.so \
	vendor/huawei/hws7300u/proprietary/lib/libqdp.so:system/lib/libqdp.so \
	vendor/huawei/hws7300u/proprietary/lib/libqueue.so:system/lib/libqueue.so \
	vendor/huawei/hws7300u/proprietary/lib/libril-qc-qmi-1.so:system/lib/libril-qc-qmi-1.so \
	vendor/huawei/hws7300u/proprietary/lib/libril-qcril-hook-oem.so:system/lib/libril-qcril-hook-oem.so \
	vendor/huawei/hws7300u/proprietary/lib/libdsutils.so:system/lib/libdsutils.so \
	vendor/huawei/hws7300u/proprietary/lib/libdsi_netctrl.so:system/lib/libdsi_netctrl.so \
	vendor/huawei/hws7300u/proprietary/lib/libidl.so:system/lib/libidl.so \
	vendor/huawei/hws7300u/proprietary/lib/libnetmgr.so:system/lib/libnetmgr.so \
	vendor/huawei/hws7300u/proprietary/etc/loc_parameter.ini:system/etc/loc_parameter.ini \
	vendor/huawei/hws7300u/proprietary/bin/loc_api_app:system/bin/loc_api_app \
	vendor/huawei/hws7300u/proprietary/lib/liboncrpc.so:system/lib/liboncrpc.so \
	vendor/huawei/hws7300u/proprietary/lib/libgps.so:system/lib/libgps.so \
        vendor/huawei/hws7300u/proprietary/lib/libgps.utils.so:system/lib/libgps.utils.so \
	vendor/huawei/hws7300u/proprietary/lib/libloc_adapter.so:system/lib/libloc_adapter.so \
	vendor/huawei/hws7300u/proprietary/lib/libloc_api-rpc-qc.so:system/lib/libloc_api-rpc-qc.so \
	vendor/huawei/hws7300u/proprietary/lib/libloc_eng.so:system/lib/libloc_eng.so \
	vendor/huawei/hws7300u/proprietary/lib/libloc_ext.so:system/lib/libloc_ext.so \
	vendor/huawei/hws7300u/proprietary/lib/libcommondefs.so:system/lib/libcommondefs.so \
	vendor/huawei/hws7300u/proprietary/lib/libgpsone_bit_api.so:system/lib/libgpsone_bit_api.so \
	vendor/huawei/hws7300u/proprietary/lib/hw/sensors.default.so:system/lib/hw/sensors.default.so \
        vendor/huawei/hws7300u/proprietary/lib/hw/lights.msm8660.so:system/lib/hw/lights.msm8660.so \
	vendor/huawei/hws7300u/proprietary/lib/hw/lcd.default.so:system/lib/hw/lcd.default.so \
	vendor/huawei/hws7300u/proprietary/bin/sensor_daemon:system/bin/sensor_daemon \
	vendor/huawei/hws7300u/proprietary/bin/sensors.qcom:system/bin/sensors.qcom \
	vendor/huawei/hws7300u/proprietary/lib/libmmjpeg.so:system/lib/libmmjpeg.so \
	vendor/huawei/hws7300u/proprietary/lib/libgemini.so:system/lib/libgemini.so \
	vendor/huawei/hws7300u/proprietary/lib/liboemcamera.so:system/lib/liboemcamera.so \
	vendor/huawei/hws7300u/proprietary/lib/libmmipl.so:system/lib/libmmipl.so \
	vendor/huawei/hws7300u/proprietary/lib/libmmmpo.so:system/lib/libmmmpo.so \
	vendor/huawei/hws7300u/proprietary/lib/libmmstereo.so:system/lib/libmmstereo.so \
	vendor/huawei/hws7300u/proprietary/bin/mm-qcamera-daemon:system/bin/mm-qcamera-daemon \
	vendor/huawei/hws7300u/proprietary/bin/mm-qcamera-test:system/bin/mm-qcamera-test \
	vendor/huawei/hws7300u/proprietary/bin/mm-qcamera-testsuite-client:system/bin/mm-qcamera-testsuite-client \
	vendor/huawei/hws7300u/proprietary/bin/v4l2-qcamera-app:system/bin/v4l2-qcamera-app \
	vendor/huawei/hws7300u/proprietary/lib/libdiag.so:system/lib/libdiag.so \
	vendor/huawei/hws7300u/proprietary/bin/sar:system/bin/sar \
	vendor/huawei/hws7300u/proprietary/etc/audio_cal.acdb:system/etc/audio_cal.acdb \
	vendor/huawei/hws7300u/proprietary/etc/audio_cal_bs300.acdb:system/etc/audio_cal_bs300.acdb \
	vendor/huawei/hws7300u/proprietary/bin/brcm_patchram_plus:system/bin/brcm_patchram_plus \
	vendor/huawei/hws7300u/proprietary/bin/hw_cifs:system/bin/hw_cifs \
	vendor/huawei/hws7300u/proprietary/bin/btnvtool:system/bin/btnvtool \
	vendor/huawei/hws7300u/proprietary/bin/mpdecision:system/bin/mpdecision \
	vendor/huawei/hws7300u/proprietary/bin/diagd:system/bin/diagd \
	vendor/huawei/hws7300u/proprietary/bin/mm-jps-enc-test:system/bin/mm-jps-enc-test \
	vendor/huawei/hws7300u/proprietary/bin/radish:system/bin/radish \
	vendor/huawei/hws7300u/proprietary/bin/curl:system/bin/curl \
	vendor/huawei/hws7300u/proprietary/bin/sapd:system/bin/sapd \
	vendor/huawei/hws7300u/proprietary/bin/mm-audio-alsa-test:system/bin/mm-audio-alsa-test \
	vendor/huawei/hws7300u/proprietary/bin/dun-server:system/bin/dun-server \
	vendor/huawei/hws7300u/proprietary/bin/test_gemini:system/bin/test_gemini \
	vendor/huawei/hws7300u/proprietary/bin/amploader:system/bin/amploader \
	vendor/huawei/hws7300u/proprietary/bin/thermald:system/bin/thermald \
	vendor/huawei/hws7300u/proprietary/bin/ccid_daemon:system/bin/ccid_daemon \
	vendor/huawei/hws7300u/proprietary/bin/port-bridge:system/bin/port-bridge \
	vendor/huawei/hws7300u/proprietary/bin/acdbtest:system/bin/acdbtest \
	vendor/huawei/hws7300u/proprietary/bin/profiler_daemon:system/bin/profiler_daemon \
	vendor/huawei/hws7300u/proprietary/bin/usbhub_init:system/bin/usbhub_init \
	vendor/huawei/hws7300u/proprietary/bin/tptest:system/bin/tptest \
	vendor/huawei/hws7300u/proprietary/bin/fmconfig:system/bin/fmconfig \
	vendor/huawei/hws7300u/proprietary/bin/diag_uart_log:system/bin/diag_uart_log \
	vendor/huawei/hws7300u/proprietary/bin/ATFWD-daemon:system/bin/ATFWD-daemon \
	vendor/huawei/hws7300u/proprietary/bin/oem_rapid:system/bin/oem_rapid \
	vendor/huawei/hws7300u/proprietary/bin/load_logo:system/bin/load_logo \
	vendor/huawei/hws7300u/proprietary/bin/usbhub:system/bin/usbhub \
	vendor/huawei/hws7300u/proprietary/bin/filebackup:system/bin/filebackup \
	vendor/huawei/hws7300u/proprietary/bin/nl_listener:system/bin/nl_listener \
	vendor/huawei/hws7300u/proprietary/bin/ftmdaemon:system/bin/ftmdaemon \
	vendor/huawei/hws7300u/proprietary/bin/pcscd:system/bin/pcscd \
	vendor/huawei/hws7300u/proprietary/bin/testpcsc:system/bin/testpcsc \
	vendor/huawei/hws7300u/proprietary/bin/ds_fmc_appd:system/bin/ds_fmc_appd \
	vendor/huawei/hws7300u/proprietary/bin/mkfs.ext4:system/bin/mkfs.ext4 \
	vendor/huawei/hws7300u/proprietary/bin/bridgemgrd:system/bin/bridgemgrd \
	vendor/huawei/hws7300u/proprietary/bin/hw_rm:system/bin/hw_rm \
	vendor/huawei/hws7300u/proprietary/lib/libdsm.so:system/lib/libdsm.so \
	vendor/huawei/hws7300u/proprietary/lib/libpbmlib_fusion.so:system/lib/libpbmlib_fusion.so \
	vendor/huawei/hws7300u/proprietary/lib/libtime_genoff.so:system/lib/libtime_genoff.so \
	vendor/huawei/hws7300u/proprietary/lib/libhwrpc.so:system/lib/libhwrpc.so \
	vendor/huawei/hws7300u/proprietary/lib/libdsucsdappif_apis_fusion.so:system/lib/libdsucsdappif_apis_fusion.so \
	vendor/huawei/hws7300u/proprietary/lib/liboem_rapi.so:system/lib/liboem_rapi.so \
	vendor/huawei/hws7300u/proprietary/lib/libmmmpod.so:system/lib/libmmmpod.so \
	vendor/huawei/hws7300u/proprietary/lib/libnode.so:system/lib/libnode.so \
	vendor/huawei/hws7300u/proprietary/lib/libmmjps.so:system/lib/libmmjps.so \
	vendor/huawei/hws7300u/proprietary/lib/libxml.so:system/lib/libxml.so \
	vendor/huawei/hws7300u/proprietary/lib/libcurl.so:system/lib/libcurl.so \
	vendor/huawei/hws7300u/proprietary/lib/libbson.so:system/lib/libbson.so \
	vendor/huawei/hws7300u/proprietary/lib/libtime_remote_atom.so:system/lib/libtime_remote_atom.so \
	vendor/huawei/hws7300u/proprietary/lib/libnv.so:system/lib/libnv.so \
	vendor/huawei/hws7300u/proprietary/lib/libNimsWrap.so:system/lib/libNimsWrap.so \
	vendor/huawei/hws7300u/proprietary/lib/liboem_rapi_fusion.so:system/lib/liboem_rapi_fusion.so \
	vendor/huawei/hws7300u/proprietary/lib/lib_iec_60958_61937.so:system/lib/lib_iec_60958_61937.so \
	vendor/huawei/hws7300u/proprietary/lib/libthermal_mitigation_fusion.so:system/lib/libthermal_mitigation_fusion.so \
	vendor/huawei/hws7300u/proprietary/lib/libconfigdb.so:system/lib/libconfigdb.so \
	vendor/huawei/hws7300u/proprietary/lib/libulp.so:system/lib/libulp.so \
	vendor/huawei/hws7300u/proprietary/lib/libqc-opt.so:system/lib/libqc-opt.so \
	vendor/huawei/hws7300u/proprietary/lib/libprofiler_msmadc.so:system/lib/libprofiler_msmadc.so \
	vendor/huawei/hws7300u/proprietary/lib/libxt_v01.so:system/lib/libxt_v01.so \
	vendor/huawei/hws7300u/proprietary/lib/libping_apps.so:system/lib/libping_apps.so \
	vendor/huawei/hws7300u/proprietary/lib/libdss.so:system/lib/libdss.so \
	vendor/huawei/hws7300u/proprietary/lib/liballjoyn.so:system/lib/liballjoyn.so \
	vendor/huawei/hws7300u/proprietary/lib/libdsprofile.so:system/lib/libdsprofile.so \
	vendor/huawei/hws7300u/proprietary/lib/libping_lte_rpc.so:system/lib/libping_lte_rpc.so \
	vendor/huawei/hws7300u/proprietary/lib/libping_mdm.so:system/lib/libping_mdm.so \
	vendor/huawei/hws7300u/proprietary/lib/liboeminfo.so:system/lib/liboeminfo.so \
	vendor/huawei/hws7300u/proprietary/lib/libthermal_mitigation.so:system/lib/libthermal_mitigation.so \
	vendor/huawei/hws7300u/proprietary/lib/libWVphoneAPI.so:system/lib/libWVphoneAPI.so \
	vendor/huawei/hws7300u/proprietary/lib/libmm-color-convertor.so:system/lib/libmm-color-convertor.so \
	vendor/huawei/hws7300u/proprietary/lib/libdtsprocessing.so:system/lib/libdtsprocessing.so \
	vendor/huawei/hws7300u/proprietary/lib/libnetmonitor.so:system/lib/libnetmonitor.so \
	vendor/huawei/hws7300u/proprietary/lib/libulp2.so:system/lib/libulp2.so \
	vendor/huawei/hws7300u/proprietary/lib/libmm-abl.so:system/lib/libmm-abl.so \
	vendor/huawei/hws7300u/proprietary/bin/mm-abl-daemon:system/bin/mm-abl-daemon \

